# Diff_file_Loading

## csv

In [1]:
import pandas as pd

In [3]:
df= pd.read_csv('/content/sample_data/student_data (1).csv')


print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [5]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

## Excel

In [9]:
df2=pd.read_excel('/content/sample_data/phitron_student_marks.xlsx')
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [10]:
df2

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

# Creating_dataframe

## from_list

In [4]:
lst = ["Apple","Orange","Papaya","Banana","Pineapple","Coconut",30,60,90]

df=pd.DataFrame(lst)
df

           0
0      Apple
1     Orange
2     Papaya
3     Banana
4  Pineapple
5    Coconut
6         30
7         60
8         90

## from_morelist_onedataframe

In [5]:
import pandas as pd

name = ["Naim","Rahim","Karim","Sakib","Rifat",
        "Hasan","Jamil","Tanvir","Arif","Nabil"]

age = [21,22,23,20,24,25,22,21,23,24]

department = ["SWE","CSE","EEE","BBA","ENG",
              "SWE","CSE","EEE","BBA","ENG"]

cgpa = [3.75,3.80,3.60,3.50,3.90,
        3.40,3.70,3.65,3.85,3.55]

df = pd.DataFrame(
    [name, age, department, cgpa],

    index=["Name","Age","Department","CGPA"]
)

print(df.T) #make transpose

     Name Age Department  CGPA
0    Naim  21        SWE  3.75
1   Rahim  22        CSE   3.8
2   Karim  23        EEE   3.6
3   Sakib  20        BBA   3.5
4   Rifat  24        ENG   3.9
5   Hasan  25        SWE   3.4
6   Jamil  22        CSE   3.7
7  Tanvir  21        EEE  3.65
8    Arif  23        BBA  3.85
9   Nabil  24        ENG  3.55

## from_numpy_array

In [6]:
import numpy as np
data = { 'A': np.array([1, 4, 7]),
         'B': np.array([2, 5, 8]),
         'C': np.array([3, 6, 9]) }
df = pd.DataFrame(data)
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

## from_list of Dict

In [7]:
data = [
    {'name': 'Mike', 'degree': 'MBA', 'score': 90},
    {'name': 'Dan', 'degree': 'BCA', 'score': 40},
    {'name': 'Emilia', 'degree': 'M.Tech', 'score': 80},
]
df = pd.DataFrame(data)
df

     name  degree  score
0    Mike     MBA     90
1     Dan     BCA     40
2  Emilia  M.Tech     80

# Viewing_dataframe

df.head()

df.tail()

df.sample()

df.shape

df.columns

df.index

df.info()

df.describe()
df.memory_usage()
df.value_counts()

In [11]:
df2.head(5)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram

In [27]:
df2.tail()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [28]:
df2.sample()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna

In [29]:
df2.shape

(20, 9)

In [30]:
df2.columns

Index(['StudentID', 'FullName', 'Data Structure Marks', 'Algorithm Marks',
       'Python Marks', 'CompletionStatus', 'EnrollmentDate', 'Instructor',
       'Location'],
      dtype='object')

In [31]:
df2.index

RangeIndex(start=0, stop=20, step=1)

In [32]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   StudentID             20 non-null     object
 1   FullName              20 non-null     object
 2   Data Structure Marks  16 non-null     float64
 3   Algorithm Marks       16 non-null     float64
 4   Python Marks          15 non-null     float64
 5   CompletionStatus      20 non-null     object
 6   EnrollmentDate        20 non-null     object
 7   Instructor            20 non-null     object
 8   Location              20 non-null     object
dtypes: float64(3), object(6)
memory usage: 1.5+ KB

In [33]:
df2.describe()

       Data Structure Marks  Algorithm Marks  Python Marks
count             16.000000        16.000000     15.000000
mean              84.000000        84.000000     85.666667
std                6.501282         6.501282      5.394000
min               72.000000        72.000000     76.000000
25%               79.500000        79.500000     83.000000
50%               85.500000        85.500000     85.000000
75%               88.250000        88.250000     88.500000
max               94.000000        94.000000     95.000000

In [12]:
df2.value_counts()

StudentID  FullName          Data Structure Marks  Algorithm Marks  Python Marks  CompletionStatus  EnrollmentDate  Instructor  Location
PH1001     Alif Rahman       85.0                  85.0             88.0          Completed         2024-01-15      Mr. Karim   Dhaka         1
PH1003     Imran Hossain     88.0                  88.0             85.0          Completed         2024-02-10      Mr. Karim   Dhaka         1
PH1004     Jannatul Ferdous  78.0                  78.0             82.0          Completed         2024-02-12      Ms. Salma   Sylhet        1
PH1006     Laila Begum       75.0                  75.0             78.0          Completed         2024-03-08      Ms. Salma   Rajshahi      1
PH1008     Nadia Islam       81.0                  81.0             85.0          Completed         2024-04-22      Ms. Salma   Chattogram    1
PH1009     Omar Faruq        72.0                  72.0             76.0          Completed         2024-05-16      Mr. David   Dhaka         1
PH1010     Priya Sharma      89.0                  89.0             88.0          Completed         2024-05-20      Ms. Salma   Sylhet        1
PH1012     Sadia Chowdhury   85.0                  85.0             87.0          Completed         2024-06-14      Ms. Salma   Chattogram    1
PH1013     Tanvir Ahmed      75.0                  75.0             79.0          Completed         2024-07-02      Mr. David   Dhaka         1
PH1015     Wahiduzzaman      86.0                  86.0             84.0          Completed         2024-08-18      Mr. Karim   Dhaka         1
PH1017     Afsana Mimi       90.0                  90.0             93.0          Completed         2025-09-01      Mr. Karim   Dhaka         1
PH1018     Babul Ahmed       88.0                  88.0             85.0          Completed         2025-09-05      Ms. Salma   Sylhet        1
PH1020     Nasir Khan        86.0                  86.0             89.0          Completed         2025-10-02      Ms. Salma   Dhaka         1
Name: count, dtype: int64

In [37]:
df2.memory_usage()

Index                   132
StudentID               160
FullName                160
Data Structure Marks    160
Algorithm Marks         160
Python Marks            160
CompletionStatus        160
EnrollmentDate          160
Instructor              160
Location                160
dtype: int64

# Accessing_Dataframe

## **iloc**

## single_row

In [38]:
df2.iloc[0]

StudentID                    PH1001
FullName                Alif Rahman
Data Structure Marks           85.0
Algorithm Marks                85.0
Python Marks                   88.0
CompletionStatus          Completed
EnrollmentDate           2024-01-15
Instructor                Mr. Karim
Location                      Dhaka
Name: 0, dtype: object

## multiple_row

In [41]:
df2.iloc[[0,2,3,9]]

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet

## row_in_range

In [43]:
df.iloc[2:8].T

  Department  CGPA
0        SWE  3.75
1        CSE   3.8
2        EEE   3.6
3        BBA   3.5
4        ENG   3.9
5        SWE   3.4
6        CSE   3.7
7        EEE  3.65
8        BBA  3.85
9        ENG  3.55

## single_col

In [45]:
df2.iloc[:,3].head()

0    85.0
1    92.0
2    88.0
3    78.0
4     NaN
Name: Algorithm Marks, dtype: float64

## multiple_col

In [47]:
df2.iloc[:,[0,2,3]].head()

  StudentID  Data Structure Marks  Algorithm Marks
0    PH1001                  85.0             85.0
1    PH1002                  92.0             92.0
2    PH1003                  88.0             88.0
3    PH1004                  78.0             78.0
4    PH1005                   NaN              NaN

## specific_cells

In [48]:
df2.iloc[3,3] # row x col val

np.float64(78.0)

## multiple_row_col

In [50]:
df2.iloc[
    0:14,
    0:4]

   StudentID          FullName  Data Structure Marks  Algorithm Marks
0     PH1001       Alif Rahman                  85.0             85.0
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN

## **loc**

## **single_row**

In [52]:
df2.loc

0     2024-01-15
1     2024-01-20
2     2024-02-10
3     2024-02-12
4     2024-03-05
5     2024-03-08
6     2024-04-01
7     2024-04-22
8     2024-05-16
9     2024-05-20
10    2024-06-11
11    2024-06-14
12    2024-07-02
13    2024-07-09
14    2024-08-18
15    2024-08-21
16    2025-09-01
17    2025-09-05
18    2025-09-15
19    2025-10-02
Name: EnrollmentDate, dtype: object

## multiple row

In [14]:
df2.loc[[3,4,5,9,15]]

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram

## row in range

In [15]:
df2.loc[3:7]

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram

## single row

In [20]:
df2.loc[:,['Algorithm Marks']]

    Algorithm Marks
0              85.0
1              92.0
2              88.0
3              78.0
4               NaN
5              75.0
6              80.0
7              81.0
8              72.0
9              89.0
10              NaN
11             85.0
12             75.0
13              NaN
14             86.0
15             94.0
16             90.0
17             88.0
18              NaN
19             86.0

## multiple col

In [21]:
df2.loc[:,['Algorithm Marks','Data Structure Marks']]

    Algorithm Marks  Data Structure Marks
0              85.0                  85.0
1              92.0                  92.0
2              88.0                  88.0
3              78.0                  78.0
4               NaN                   NaN
5              75.0                  75.0
6              80.0                  80.0
7              81.0                  81.0
8              72.0                  72.0
9              89.0                  89.0
10              NaN                   NaN
11             85.0                  85.0
12             75.0                  75.0
13              NaN                   NaN
14             86.0                  86.0
15             94.0                  94.0
16             90.0                  90.0
17             88.0                  88.0
18              NaN                   NaN
19             86.0                  86.0

## all rows cols

In [22]:
df2.loc[:,:]

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

# Changing index and columns

In [27]:
df2.rename(columns={'FullName':'Full Name','Algorithm Marks' :'Algo Marks'},inplace=True)

df2.head()

,StudentID,Full Name,Data Structure Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram

# Row deletion

In [30]:
df2.drop(2,inplace=True)
df2

,StudentID,Full Name,Data Structure Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

# col deletion

In [36]:
df2.drop('Location',axis=1, inplace=True)
df2.head(4)

,StudentID,Full Name,Data Structure Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01

# change_index_val

In [40]:
df.loc[7,'Python Marks'] = 60

df.loc[7,'CompletionStatus'] = 'In progress'
df.head(5)

     name  degree  score  Python Marks CompletionStatus
0    Mike     MBA   90.0           NaN              NaN
1     Dan     BCA   40.0          90.0        Completed
2  Emilia  M.Tech   80.0           NaN              NaN
7     NaN     NaN    NaN          60.0      In progress

# Iteration

In [41]:
for i,series in df.iterrows():
    print( f"{i} : {series}")

0 : name                Mike
degree               MBA
score               90.0
Python Marks         NaN
CompletionStatus     NaN
Name: 0, dtype: object
1 : name                      Dan
degree                    BCA
score                    40.0
Python Marks             90.0
CompletionStatus    Completed
Name: 1, dtype: object
2 : name                Emilia
degree              M.Tech
score                 80.0
Python Marks           NaN
CompletionStatus       NaN
Name: 2, dtype: object
7 : name                        NaN
degree                      NaN
score                       NaN
Python Marks               60.0
CompletionStatus    In progress
Name: 7, dtype: object

In [42]:
for i in df.itertuples(index=False):
    print(i)

Pandas(name='Mike', degree='MBA', score=90.0, _3=nan, CompletionStatus=nan)
Pandas(name='Dan', degree='BCA', score=40.0, _3=90.0, CompletionStatus='Completed')
Pandas(name='Emilia', degree='M.Tech', score=80.0, _3=nan, CompletionStatus=nan)
Pandas(name=nan, degree=nan, score=nan, _3=60.0, CompletionStatus='In progress')